apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-ingress-controller
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: aws-alb-ingress-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: aws-alb-ingress-controller
    repoURL: https://kubernetes-charts-incubator.storage.googleapis.com
    targetRevision: 1.0.2
