apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: kubesystem
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/cluster-addons/cluster-autoscaler/
    repoURL: https://github.com/sj-sayers/k8s-env.git
    targetRevision: v0.8.3
